name: react-ui-kit unit tests

on:
  push:
    branches: [master, nextjs]
  pull_request:
    branches: [master, dev]

jobs:
  test_code:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Clean install dependencies
        working-directory: ./CometChatWorkspace
        run: npm ci
      - name: Run test cases
        working-directory: ./CometChatWorkspace
        run: npm test
